// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/perception/lidar/lib/segmentation/ncut/proto/ncut_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2flidar_2flib_2fsegmentation_2fncut_2fproto_2fncut_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2flidar_2flib_2fsegmentation_2fncut_2fproto_2fncut_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_modules_2fperception_2flidar_2flib_2fsegmentation_2fncut_2fproto_2fncut_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_modules_2fperception_2flidar_2flib_2fsegmentation_2fncut_2fproto_2fncut_5fconfig_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2fperception_2flidar_2flib_2fsegmentation_2fncut_2fproto_2fncut_5fconfig_2eproto;
namespace apollo {
namespace perception {
namespace lidar {
class NCutConfig;
class NCutConfigDefaultTypeInternal;
extern NCutConfigDefaultTypeInternal _NCutConfig_default_instance_;
}  // namespace lidar
}  // namespace perception
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> ::apollo::perception::lidar::NCutConfig* Arena::CreateMaybeMessage<::apollo::perception::lidar::NCutConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apollo {
namespace perception {
namespace lidar {

// ===================================================================

class NCutConfig :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.perception.lidar.NCutConfig) */ {
 public:
  NCutConfig();
  virtual ~NCutConfig();

  NCutConfig(const NCutConfig& from);
  NCutConfig(NCutConfig&& from) noexcept
    : NCutConfig() {
    *this = ::std::move(from);
  }

  inline NCutConfig& operator=(const NCutConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline NCutConfig& operator=(NCutConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NCutConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NCutConfig* internal_default_instance() {
    return reinterpret_cast<const NCutConfig*>(
               &_NCutConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NCutConfig& a, NCutConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(NCutConfig* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NCutConfig* New() const final {
    return CreateMaybeMessage<NCutConfig>(nullptr);
  }

  NCutConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NCutConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NCutConfig& from);
  void MergeFrom(const NCutConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NCutConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.perception.lidar.NCutConfig";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_modules_2fperception_2flidar_2flib_2fsegmentation_2fncut_2fproto_2fncut_5fconfig_2eproto);
    return ::descriptor_table_modules_2fperception_2flidar_2flib_2fsegmentation_2fncut_2fproto_2fncut_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParamFileFieldNumber = 1,
  };
  // optional string param_file = 1 [default = "./data/models/ncut/param.conf"];
  bool has_param_file() const;
  private:
  bool _internal_has_param_file() const;
  public:
  void clear_param_file();
  const std::string& param_file() const;
  void set_param_file(const std::string& value);
  void set_param_file(std::string&& value);
  void set_param_file(const char* value);
  void set_param_file(const char* value, size_t size);
  std::string* mutable_param_file();
  std::string* release_param_file();
  void set_allocated_param_file(std::string* param_file);
  private:
  const std::string& _internal_param_file() const;
  void _internal_set_param_file(const std::string& value);
  std::string* _internal_mutable_param_file();
  public:

  // @@protoc_insertion_point(class_scope:apollo.perception.lidar.NCutConfig)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  public:
  static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> _i_give_permission_to_break_this_code_default_param_file_;
  private:
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr param_file_;
  friend struct ::TableStruct_modules_2fperception_2flidar_2flib_2fsegmentation_2fncut_2fproto_2fncut_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NCutConfig

// optional string param_file = 1 [default = "./data/models/ncut/param.conf"];
inline bool NCutConfig::_internal_has_param_file() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool NCutConfig::has_param_file() const {
  return _internal_has_param_file();
}
inline void NCutConfig::clear_param_file() {
  param_file_.ClearToDefaultNoArena(&::apollo::perception::lidar::NCutConfig::_i_give_permission_to_break_this_code_default_param_file_.get());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& NCutConfig::param_file() const {
  // @@protoc_insertion_point(field_get:apollo.perception.lidar.NCutConfig.param_file)
  return _internal_param_file();
}
inline void NCutConfig::set_param_file(const std::string& value) {
  _internal_set_param_file(value);
  // @@protoc_insertion_point(field_set:apollo.perception.lidar.NCutConfig.param_file)
}
inline std::string* NCutConfig::mutable_param_file() {
  // @@protoc_insertion_point(field_mutable:apollo.perception.lidar.NCutConfig.param_file)
  return _internal_mutable_param_file();
}
inline const std::string& NCutConfig::_internal_param_file() const {
  return param_file_.GetNoArena();
}
inline void NCutConfig::_internal_set_param_file(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  param_file_.SetNoArena(&::apollo::perception::lidar::NCutConfig::_i_give_permission_to_break_this_code_default_param_file_.get(), value);
}
inline void NCutConfig::set_param_file(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  param_file_.SetNoArena(
    &::apollo::perception::lidar::NCutConfig::_i_give_permission_to_break_this_code_default_param_file_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.perception.lidar.NCutConfig.param_file)
}
inline void NCutConfig::set_param_file(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  param_file_.SetNoArena(&::apollo::perception::lidar::NCutConfig::_i_give_permission_to_break_this_code_default_param_file_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.perception.lidar.NCutConfig.param_file)
}
inline void NCutConfig::set_param_file(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  param_file_.SetNoArena(&::apollo::perception::lidar::NCutConfig::_i_give_permission_to_break_this_code_default_param_file_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.perception.lidar.NCutConfig.param_file)
}
inline std::string* NCutConfig::_internal_mutable_param_file() {
  _has_bits_[0] |= 0x00000001u;
  return param_file_.MutableNoArena(&::apollo::perception::lidar::NCutConfig::_i_give_permission_to_break_this_code_default_param_file_.get());
}
inline std::string* NCutConfig::release_param_file() {
  // @@protoc_insertion_point(field_release:apollo.perception.lidar.NCutConfig.param_file)
  if (!_internal_has_param_file()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return param_file_.ReleaseNonDefaultNoArena(&::apollo::perception::lidar::NCutConfig::_i_give_permission_to_break_this_code_default_param_file_.get());
}
inline void NCutConfig::set_allocated_param_file(std::string* param_file) {
  if (param_file != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  param_file_.SetAllocatedNoArena(&::apollo::perception::lidar::NCutConfig::_i_give_permission_to_break_this_code_default_param_file_.get(), param_file);
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.lidar.NCutConfig.param_file)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace lidar
}  // namespace perception
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2flidar_2flib_2fsegmentation_2fncut_2fproto_2fncut_5fconfig_2eproto
